#!/bin/sh

#==================================================================================================
#title           :containerstat
#description     :parse containerstat from client
#author          :Wesley van Tilburg
#date            :27/09/2022
#version         :1
#==================================================================================================

run(){
	. $INTEGRATIONDIR/influx
	tjson="$(echo $msg | jq -c '.containers []' 2>/dev/null)"
	if ! [ -z "$tjson" ]; then
		 while read -r line
		do
			name="$(echo $line | jq -r '.name')"
			status="$(echo $line | jq -r '.status' | cut -d' ' -f2-6)"
			DATA="$TNAME,hostname=$HOST,container=$name status=\"$status\""
			influx_push
		done < <(echo -e "$tjson")
	fi
}
