#!/bin/sh

#==================================================================================================
#title           :ports
#description     :parse ports from client
#author          :Wesley van Tilburg
#date            :03/10/2022
#version         :1
#==================================================================================================

run(){
	. $INTEGRATIONDIR/influx
	tjson="$(echo $msg | jq -rc '.ports []' 2>/dev/null)"
	if ! [ -z "$tjson" ]; then
		while read -r line
		do
			port="$(echo $line | jq -r '.port')"
			if nc -z -v "$IP" "$port" &>/dev/null; then
				status="UP"
			else
				status="Down"
			fi
			DATA="$TNAME,hostname=$HOST,port=$port status=\"$status\""
			influx_push
		done < <(echo -e "$tjson")
	fi
}
