#!/bin/sh

#==================================================================================================
#title           :sysinfo
#description     :parse sysinfo from client
#author          :Wesley van Tilburg
#date            :18/09/2022
#version         :1
#==================================================================================================

run(){
	tjson="$(echo $msg | jq -r '.system')"
	CPU="$(echo $tjson | jq -r '.cpu' | tr -d ' ')"
	RAM="$(echo $tjson | jq -r '.ram')"
	STORAGE="$(echo $tjson | jq -r  '.storage')"
	UPTIME="$(echo $tjson | jq -r '.uptime')"
	DATA="$TNAME,hostname=$HOST cpu=$CPU,ram=$RAM,storage=$STORAGE"

	. $INTEGRATIONDIR/influx
  influx_push
}
