{
 "title": "MiniMon",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU usage %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"MiniMon\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sysinfo\")\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n\n  "
    }
   ]
  },
  {
   "title": "RAM usage %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"MiniMon\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sysinfo\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ram\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Storage usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"MiniMon\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sysinfo\")\n  |> filter(fn: (r) => r[\"_field\"] == \"storage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Current Container status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"MiniMon\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"containerstat\")\n  |>unique()\n  |> group()\n  |> drop(columns: [\"_measurement\",\"_start\",\"_stop\",\"_time\",\"_field\"] )"
    }
   ]
  },
  {
   "title": "Current service status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"MiniMon\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ports\")\n  |>unique()\n  |> group()\n  |> drop(columns: [\"_measurement\",\"_start\",\"_stop\",\"_time\",\"_field\"] )\n  "
    }
   ]
  }
 ]
}