#!/bin/sh
set  -m -o pipefail

#==================================================================================================
#title           :minimon-client
#description     :Client for minimon
#author          :Wesley van Tilburg
#date            :13/09/2022
#version         :0.1
#==================================================================================================

trap 'clean' EXIT SIGINT SIGTERM

clean(){
		if $STARTED; then
			kill -- -$(jobs -p)
		fi
		rm -rf /tmp/minimon-in
		rm -rf /tmp/minimon-jobs
		exit 0
}

#Log functions
log(){ printf '\e[0;%sm[\e[0m%s\e[0;%sm]\e[0m %s\n' "${3:-35}" "$(date)" "${3:-35}" "$1"; }
warn(){ log "$1" "${2:-warning}" 33; }
err(){ log "$1" "${2:-error}" 31; exit 1; }

usage(){
	echo "MiniMon; made by Misthios
-i : ip off the server
-p : port off the server (defaults to 12345)
-c : path for the certificate
-v : verify the certificate (defaults to 0 = false
-d : delay for the metrics in seconds (defaults to 15)
-t : folder which contains the tasks shell scripts (defaults to ./Tasks)
";}


#run all the tasks and concat the json output to form the end data
gen_json(){
	for task in $TASKS 
	do
		. $task
		run #sourced_function
       		JSON="$(echo "$JSON $tjson" | jq -s add )"
	done
	
}

#write the json to the tmp file which socat tails for new data
post_json(){
	echo $JSON >> /tmp/minimon-in

}

setup(){
	if ! [ -d "$TASKDIR" ]; then err "taskdir does not exist";  fi
	TASKS="$(find "$TASKDIR" -type f -maxdepth 1)"
	touch /tmp/minimon-in

}

run_server(){
	tail -f /tmp/minimon-in | socat stdio openssl-connect:"$IP":"$PORT",cert="$CERT",verify="$VERIFY" 2>/dev/null
}
 

main(){
setup
log "starting minimon..."
run_server&
#---------- Ugly way to detect connection failure by checking bg job status-----------#
sleep 5 #give socat time to connect
echo $(jobs) >> /tmp/minimon-jobs
if ! cat /tmp/minimon-jobs | grep -qi "Running"; then err "failed to connect aborting..."; fi
#-------------------------------------------------------------------------------------#
STARTED=true
log "started minimon"


#main loop
while :
do
	#make sure that the background job is still running
	echo $(jobs) > /tmp/minimon-jobs
	if ! cat /tmp/minimon-jobs | grep -qi "Running"; then err "Lost connection with the server aborting.."; fi

	gen_json
	post_json
	sleep $DELAY
done

}

#--------- ARGUMENTS ----------#
while getopts ':i:t:p:d:c:v:h' OPTION; do
	case "$OPTION" in
		i) IP="$OPTARG";;
		p) PORT="$OPTARG";;
		d) DELAY="$OPTARG";;
		c) CERT="$OPTARG";;
		t) TASKDIR="$OPTARG";;
		v) VERIFY="$OPTARG";;
		h) usage; exit 0;;
	esac
done

#default values
: ${PORT:="12345"}
: ${DELAY:=15}
: ${TASKDIR:="./Tasks/"}
: ${VERIFY:=0} #off by default for now
STARTED=false


#Make sure we have the required params
if [ -z "$IP" ]; then err "A ip must be given";  fi;

#Make sure that cert is a valid pem file
if [ -z "$CERT" ]; then err "A cert path must be given"; fi;
if ! [ -f "$CERT" ]; then err "cert not found"; fi;
if ! openssl x509 --noout -in "$CERT"; then err "cert is not a valid pem"; fi;

#Make sure that verify is a number
re='^[0-9]+$'
if ! [[ $VERIFY =~ $re ]] ; then err "Verify must be a number" ; fi
if ! [ "$VERIFY" -ge 0 ] && ["$VERIFY" -le 1 ]; then err "verify must either be 0 or 1"; fi;

main
