#!/bin/sh
set -m

#==================================================================================================
#title           :minimon-server
#description     :Server for minimon
#author          :Wesley van Tilburg
#date            :13/09/2022
#version         :0.05
#==================================================================================================

trap 'clean' EXIT SIGINT SIGTERM

clean(){
	if $STARTED; then
		kill -- -$(jobs -p)
		rm -rf /tmp/mini*
		exit 0
	fi
}

#Log functions
log(){ printf '\e[0;%sm[\e[0m%s\e[0;%sm]\e[0m %s\n' "${3:-35}" "$(date)" "${3:-35}" "$1"; }
warn(){ log "$1" "${2:-warning}" 33; }
err(){ log "$1" "${2:-error}" 31; exit 1; }

usage(){
	echo "MiniMon; made by Misthios
-p : port for the server (defaults to 12345)
-c : path for the certificate
-v : verify the certificate (defaults to 0 = false)
-t : folder which contains the tasks shell scripts (defaults to ./Tasks/)
";}

setup(){
	mkdir -p /tmp/minimon/hosts/
	if ! [ -e /tmp/minimon/control ]; then mkfifo /tmp/minimon/control; fi
	TASKS="$(find "$TASKDIR" -type f -maxdepth 1)"

}


run_server(){
	 socat -u openssl-listen:"$PORT",fork,reuseaddr,cert="$CERT",verify="$VERIFY" \
	 'system:
			read MESSAGE
			name=$(echo $MESSAGE | jq -r ".host")
			echo connect $name $SOCAT_PEERADDR >> /tmp/minimon/control

	 	while read MESSAGE
		do
			echo $MESSAGE >> /tmp/minimon/hosts/$name
		done
		echo disconnect $name >> /tmp/minimon/control
		'
	
}

#Read the hosts metrics
listen(){

	hosttasks="$(find "$TASKDIR$1" -type f -maxdepth 1)"
	TASKS="$TASKS $hosttasks"
		
	while read msg < /tmp/minimon/hosts/$1
	do
		for task in $TASKS
		do
			. $task
			run
		done
	done
}

#start a background job to read the hosts metrics
listen_control(){
	while :
	do
		read msg < /tmp/minimon/control
		name="$(echo $msg | cut -d' ' -f2)"
		case "$msg" in
			connect*) 
				  pipe="/tmp/minimon/hosts/$name"
				  ip="$(echo $msg | cut -d' ' -f3)"
				  if ! [ -e "$pipe" ]; then 
					  log "New host: $name"
					  mkfifo /tmp/minimon/hosts/"$name"
					  listen $name&
				  else 
					  log "$name reconnected"
				  fi
				  CURR_HOSTS="$CURR_HOSTS $name:$ip"
				  ;;
			disconnect*) 
				  log "$name disconnected"
				  old="$(echo $CURR_HOSTS | grep -o "$name.[0-9].*")"
				  CURR_HOSTS="$(echo $CURR_HOSTS | sed "s/$old//g")"
			        ;;
		 esac
	done
}

##--------- ARGUMENTS ----------#
while getopts ':p:t:c:v:h' OPTION; do
	case "$OPTION" in
		p) PORT="$OPTARG";;
		c) CERT="$OPTARG";;
		t) TASKDIR="$OPTARG";;
		v) VERIFY="$OPTARG";;
		h) usage; exit 0;;
	esac
done

#default values
: ${PORT:="12345"}
: ${TASKDIR:="./Tasks/"}
: ${VERIFY:=0} #off by gefault for now
STARTED=false
CURR_HOSTS=""


#Make sure that cert is a valid pem file
if [ -z "$CERT" ]; then err "A cert path must be given";  fi;
if ! [ -f "$CERT" ]; then err "cert not found";  fi;
if ! openssl x509 --noout -in "$CERT" 2>/dev/null; then err "cert is not a valid pem";  fi;

#Make sure that verify is a number
re='^[0-9]+$'
if ! [[ $VERIFY =~ $re ]] ; then err "Verify must be a number" ;  fi
if ! [ "$VERIFY" -ge 0 ] && ["$VERIFY" -le 1 ]; then err "verify must either be 0 or 1";  fi;

#Verify TASKDIR
if ! [ -d "$TASKDIR" ]; then err "taskdir does not exist";  fi

setup
run_server&
listen_control&
STARTED=true #for the cleanup trap

#todo: replace with shell
while :
do
	sleep 1
done


