#!/bin/sh


#Get basic system information
run(){
        UPDATED="$(date)"
        HOST="$HOSTNAME"
        CPU="$(uptime | cut -d: -f5)"
	RAM="$(free -m | awk 'NR==2{printf "%s/%sMB", $3,$2}')"
	STORAGE="$(df / -h | awk '$NF=="/"{printf "%s/%s", $3,$2}')"
        UPTIME="$(uptime -p)"
        tjson="$(jq --null-input \
                   --arg updated "$UPDATED" \
                   --arg host "$HOST" \
                   --arg cpu "$CPU" \
                   --arg ram "$RAM" \
                   --arg storage "$STORAGE" \
                   --arg uptime "$UPTIME" \
                  '{"updated" : $updated,
                    "host": $host,
                    "system": {
                        "cpu": $cpu,
                        "ram": $ram,
                        "storage": $storage,
                        "uptime": $uptime
            }}')"
}
