#!/bin/sh

#==================================================================================================
#title           :containerstat
#description     :get basic container stats
#author          :Wesley van Tilburg
#date            :27/09/2022
#version         :1
#==================================================================================================

run(){

	#check for podman/docker
	if  command -v docker &> /dev/null; then ENGINE=docker
	elif command -v podman &> /dev/null; then ENGINE=podman
	else warn "$TNAME: no container engine found"; fi

	#check if we have the required permissions
	if grep -q $(whoami) /etc/subuid; then
		if containers="$($ENGINE container ls -a --format "{{.Names}} | {{.State}} \n")"; then
			while read -r line
			do
				name="$(echo $line | cut -d'|' -f1 )"
				status="$(echo $line | cut -d'|' -f2 )"
				tjson="$(echo "$tjson" | jq \
					--arg name "$name" \
					--arg status "$status" \
					'.containers += [{"name": $name, "status" : $status}]')"
			done < <(echo -e "$containers")

		else
			warn "$TNAME: failed to retrieve containers from $ENGINE"
		fi
	else
		warn "$TNAME: user not found in /etc/subuid"
	fi
}
