#!/bin/sh

#==================================================================================================
#title           :sysinfo
#description     :get basic system information
#author          :Wesley van Tilburg
#date            :13/09/2022
#version         :1
#==================================================================================================

run(){
        UPDATED="$(date)"
        HOST="$HOSTNAME"
	CPU="$(echo 100 - $(mpstat -u | tail -1 | awk '{print $11}') | bc)"
	RAM="$(free -m | awk 'NR==2{print $3*100/$2}' | cut -c -4)"
	STORAGE="$(df / -h | awk '$NF=="/"{print  $5}' | sed 's/%//g')"
        UPTIME="$(uptime )"
	OS="$(cat /etc/os-release | grep PRETTY_NAME | cut -d= -f2 | tr -d '"')"
        tjson="$(jq --null-input \
                   --arg updated "$UPDATED" \
                   --arg host "$HOST" \
                   --arg cpu "$CPU" \
                   --arg ram "$RAM" \
                   --arg storage "$STORAGE" \
                   --arg uptime "$UPTIME" \
                   --arg os "$OS" \
                  '{"updated" : $updated,
                    "host": $host,
		    "os": $os,
                    "system": {
                        "cpu": $cpu,
                        "ram": $ram,
                        "storage": $storage,
                        "uptime": $uptime
            }}')"
}
