#!/bin/sh

#==================================================================================================
#title           :ping
#description     :check  if the host is reachable using ping
#author          :Wesley van Tilburg
#date            :19/09/2022
#version         :1
#==================================================================================================



#todo: make this configurable
TRESHOLD=15 #trigger an alert after x failed pings

run(){
  file="/tmp/minimon/monitors/ping"
  if ! [ -f $file ]; then touch $file;fi
  ping -qw 2 $ip &> /dev/null
  if ! [ "$?" -eq 0 ]; then 
    warn "$name is not reachable"
    failures="$(cat "$file" | grep "$name" | cut -d: -f2)"
    if [ -z  "$failures" ]; then 
      echo "$name:1" >> $file
    else
      old_failures=$failures
      failures=$((failures + 1 ))

      influx="$INTEGRATIONDIR/influx"
      if [ -f "$influx" ]; then
        DATA="ping,hostname=$name failures=$failures"
        . $INTEGRATIONDIR/influx
        influx_push
      fi

      if [ "$failures" -gt $TRESHOLD ]; then trigger_alarms $name "has reached the ping treshold"; sed -i "s/$name:$TRESHOLD/$name:0/" $file; fi 
      sed -i "s/$name:$old_failures/$name:$failures/g" $file
    fi
  fi
}

