#!/bin/sh


#todo: make this configurable
TRESHOLD=15 #trigger an alert after x failed pings

run(){
  file="/tmp/minimon/monitors/ping"
  if ! [ -f $file ]; then touch $file;fi
  ping -qw 2 $ip > /dev/null
  if ! [ "$?" -eq 0 ]; then 
    warn $name is not reachable
    failures="$(cat "$file" | grep "$name" | cut -d: -f2)"
    if [ -z  "$failures" ]; then 
      echo "$name:1" >> $file
    else
      old_failures=$failures
      failures=$((failures + 1 ))
        #todo: send alert when treshold is reached
      if [ "$failures" -gt $TRESHOLD ]; then warn "Alert trigger for $name";fi 
      sed -i "s/$name:$old_failures/$name:$failures/g" $file
    fi
  fi
}

